In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

In [ ]:
# Считывание данных из файла
df = pd.read_csv('data.csv', decimal=',')
A = df['A'].to_numpy()
B = df['B'].to_numpy()
Y = df['response'].to_numpy() # матрица наблбдаемых значений отклика
df

A  B  response
0   1  1      0.77
1   1  1      2.10
2   1  1      2.22
3   1  1      0.95
4   1  2      5.32
5   1  2      6.00
6   1  2      2.37
7   1  3     -2.08
8   1  3     -1.54
9   1  3     -1.29
10  1  3      0.23
11  1  3     -3.41
12  1  3      0.51
13  2  1      4.00
14  2  1      3.21
15  2  1      2.85
16  2  1      0.47
17  2  1      3.75
18  2  2      0.45
19  2  2      0.87
20  2  2      0.45
21  2  2     -0.97
22  2  3      1.32
23  2  3      1.79
24  2  3     -1.82
25  2  3      1.36
26  2  3      0.96

Модель порождения данных:

$$
y_{ijl} = \mu_{ij} + \varepsilon_{ijl}, \quad l = 1, \dots, n_{ij}, \quad i = 1, \dots, k, \quad j = 1, \dots, m, \tag{1}
$$

где:
- $y_{ijl}$ — $l$-ое наблюдаемое значение отклика для $i$-го уровня фактора $A$ и $j$-го уровня фактора $B$;  
- $\mu_{ij}$ — среднее значение отклика для $i$-го уровня фактора $A$ и $j$-го уровня фактора $B$;  
- $\varepsilon_{ijl}$ — независимые случайные величины с математическим ожиданием равным нулю и одинаковой дисперсией.


Пусть:
- $\mu$ — общее среднее;  
- $\mu_{i*}$ — среднее для $i$-го уровня фактора $A$;  
- $\mu_{*j}$ — среднее для $j$-го уровня фактора $B$.  

Тогда:
$$
\mu = \frac{1}{km} \sum_{i=1}^k \sum_{j=1}^m \mu_{ij}, \quad
\mu_{i*} = \frac{1}{m} \sum_{j=1}^m \mu_{ij}, \quad
\mu_{*j} = \frac{1}{k} \sum_{i=1}^k \mu_{ij}
$$

Далее, положим:

$$
\alpha_i = \mu_{i*} - \mu,
$$

$$
\beta_j = \mu_{*j} - \mu,
$$

$$
\gamma_{ij} = \mu_{ij} - \mu - (\alpha_i + \beta_j) = \mu_{ij} - (\mu_{i*} + \mu_{*j}) + \mu,
$$


и перепишем линейную модель в виде:

$$
y_{ijl} = \mu_{ij} + \epsilon_{ijl} = \mu + \alpha_i + \beta_j + \gamma_{ij} + \epsilon_{ijl}, \quad l = 1, n_{ij}, \quad i = 1, k, \quad j = 1, m \tag{2}
$$

- $\alpha_i$ — главный эффект i-го уровня фактора A;  
- $\beta_j$ — главный эффект j-го уровня фактора B;  
- $\gamma_{ij}$ — эффект взаимодействия i-го уровня фактора A и j-го уровня фактора B.  

Перепишем (2) терминах линейной регрессионной модели:

$$
y = \mu + \alpha_1 x_{A1} + \cdots + \alpha_k x_{Ak} + \beta_1 x_{B1} + \cdots + \beta_m x_{Bm} + \gamma_{11} x_{A1} x_{B1} + \cdots + \gamma_{km} x_{Ak} x_{Bm} + \epsilon, \tag{3}
$$

где:

$x_{Ai} = 1$, если наблюдение соответствует $i$-му уровню фактора $A$ и $x_{Ai} = 0$ иначе;

$x_{Bj} = 1$, если наблюдение соответствует $j$-му уровню фактора $B$ и $x_{Bj} = 0$ иначе.

Если используются ограничения:

$$
\sum_{i=1}^k \alpha_i = 0, \quad \sum_{j=1}^m \beta_j = 0, \quad \sum_{i=1}^k \gamma_{ij} = 0 \quad (j = \overline{1,m}), \quad \sum_{j=1}^m \gamma_{ij} = 0,
$$

(5)

то матрицу $\tilde{X}$ модели полного ранга можно построить следующим образом.

Столбцы $\tilde{x}_{A1}, \tilde{x}_{A2}, \dots, \tilde{x}_{Ak-1}, \tilde{x}_{B1}, \tilde{x}_{B2}, \dots, \tilde{x}_{Bm-1}$, соответствующие эффектам факторов $A$ и $B$, формируем также как в однофакторной модели для ограничений вида

$$
\sum_{i=1}^k \alpha_i = 0, \quad \sum_{j=1}^m \beta_j = 0.
$$

Столбцы, соответствующие эффекту взаимодействия, получаем, перемножая столбцы $\tilde{x}_{A1}, \tilde{x}_{A2}, \dots, \tilde{x}_{Ak-1}$ и $\tilde{x}_{B1}, \tilde{x}_{B2}, \dots, \tilde{x}_{Bm-1}$. Матрица $\tilde{X}$ содержит также столбец из единиц, соответствующий эффекту общего среднего.

Введем обозначения для суммы квадратов остатков линейной модели:

- $R(\mu)$ - модель с $\mu$
- $R(\mu, A)$ - модель с $\mu$ и $\alpha_i$ ($i=1,\dots,k$)
- $R(\mu, B)$ - модель с $\mu$ и $\beta_j$ ($j=1,\dots,m$)
- $R(\mu, A, B)$ - модель с $\mu$, $\alpha_i$, $\beta_j$
- $R(\mu, A, B, AB)$ - полная модель с $\mu$, $\alpha_i$, $\beta_j$, $\gamma_{ij}$

Далее, под записью $SS(A|B)$ будем понимать сумму квадратов, соответствующих эффекту фактора $A$, после исключения суммы квадратов, соответствующей эффекту фактора $B$.


Суммы квадратов I типа для двухфакторной модели с первым фактором $A$:

$$
\begin{aligned}
\text{Эффект } A &: SS(A) = R(\mu) - R(\mu, A) \\
\text{Эффект } B &: SS(B|A) = R(\mu, A) - R(\mu, A, B) \\
\text{Эффект } AB &: SS(AB|A,B) = R(\mu, A, B) - R(\mu, A, B, AB)
\end{aligned}
$$

Все суммы определяются однозначно, независимо от условий на параметры модели. Для их получения требуется построить 4 различные модели.

Статистика критерия формируется на основе F-отношения средних сумм квадратов эффекта и остатков.

In [ ]:
# Строим матрицу X

# Находим столбцы, соответствующие эффекту фактора A
X_A_init = np.zeros([len(Y), 3])
# Заполнение нулевого столбца
for row in X_A_init:
  row[0] = 1
# Заполнение первого столбца
for row_num in range(len(X_A_init)):
  if A[row_num] == 1:
    X_A_init[row_num][1] = 1
# Заполнение второго столбца
for row_num in range(len(X_A_init)):
  if A[row_num] == 2:
    X_A_init[row_num][2] = 1
X_A_init

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [ ]:
# Найдем столбец X_A1 c учётом ограничений
X_A1 = np.zeros([len(Y), 1])
# Заполнение первого столбца
for row_num in range(len(X_A_init)):
  X_A1[row_num][0] = X_A_init[row_num][1] - X_A_init[row_num][2]
X_A1

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [ ]:
# Находим столбцы, соответствующие эффекту фактора B
X_B_init = np.zeros([len(Y), 4])
# Заполнение нулевого столбца
for row in X_B_init:
  row[0] = 1
# Заполнение первого столбца
for row_num in range(len(X_B_init)):
  if B[row_num] == 1:
    X_B_init[row_num][1] = 1
# Заполнение второго столбца
for row_num in range(len(X_B_init)):
  if B[row_num] == 2:
    X_B_init[row_num][2] = 1
# Заполнение третьего столбца
for row_num in range(len(X_B_init)):
  if B[row_num] == 3:
    X_B_init[row_num][3] = 1
X_B_init

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [ ]:
# Найдём столбцы X_B1 и X_B2 c учётом ограничений
X_B1 = np.zeros([len(Y), 1])
X_B2 = np.zeros([len(Y), 1])
# Заполнение первого столбца
for row_num in range(len(X_B_init)):
  X_B1[row_num][0] = X_B_init[row_num][1] - X_B_init[row_num][2]
# Заполнение второго столбца
for row_num in range(len(X_B_init)):
  X_B2[row_num][0] = X_B_init[row_num][2] - X_B_init[row_num][3]
X_B1

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [ ]:
X_B2

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [ ]:
# Находим столбцы, соответствующие эффекту взаимодействия A и B
X_A1_B1 = X_A1 * X_B1
X_A1_B2 = X_A1 * X_B2

In [ ]:
# Находим матрицу X
X_1 = np.ones([len(Y), 1])
X = np.column_stack((X_1, X_A1, X_B1, X_B2, X_A1_B1, X_A1_B2))
X

array([[ 1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  0.,  1.,  0.],
       [ 1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  0., -1.,  0., -1.],
       [ 1.,  1.,  0., -1.,  0., -1.],
       [ 1.,  1.,  0., -1.,  0., -1.],
       [ 1.,  1.,  0., -1.,  0., -1.],
       [ 1.,  1.,  0., -1.,  0., -1.],
       [ 1.,  1.,  0., -1.,  0., -1.],
       [ 1., -1.,  1.,  0., -1., -0.],
       [ 1., -1.,  1.,  0., -1., -0.],
       [ 1., -1.,  1.,  0., -1., -0.],
       [ 1., -1.,  1.,  0., -1., -0.],
       [ 1., -1.,  1.,  0., -1., -0.],
       [ 1., -1., -1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.,  1., -1.],
       [ 1., -1.,  0., -1., -0.,  1.],
       [ 1., -1.,  0., -1., -0.,  1.],
       [ 1., -1.,  0., -1., -0.,  1.],
       [ 1., -1.,  0., -1

Матрица $\tilde{X}$ найдена. Теперь построим следующие 4 регрессионные модели:

- $R(\mu)$ - модель с $\mu$
- $R(\mu, A)$ - модель с $\mu$ и $\alpha_i$ ($i=1,\dots,k$)
- $R(\mu, A, B)$ - модель с $\mu$, $\alpha_i$, $\beta_j$
- $R(\mu, A, B, AB)$ - полная модель с $\mu$, $\alpha_i$, $\beta_j$, $\gamma_{ij}$

Нахождение вектора оценок параметров регрессии:
$$
\hat{B} = K^{-1}Z,
$$

где:

$$
K = X^TX, \quad Z = X^TY,
$$

$$
X =
\begin{pmatrix}
1 & x_1^{(1)} & \cdots & x_k^{(1)} \\
1 & x_1^{(2)} & \cdots & x_k^{(2)} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_1^{(n)} & \cdots & x_k^{(n)}
\end{pmatrix}
=
\begin{pmatrix}
1 & \varphi_1(x_1) & \cdots & \varphi_k(x_1) \\
1 & \varphi_1(x_2) & \cdots & \varphi_k(x_2) \\
\vdots & \vdots & \ddots & \vdots \\
1 & \varphi_1(x_n) & \cdots & \varphi_k(x_n)
\end{pmatrix}, \quad
Y =
\begin{pmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n
\end{pmatrix}
$$

In [ ]:
# Функция для нахождения оценки параметров уравнения множественной линейной регрессии
def mul_linear_reg_params(X, Y):
  K = X.T @ X
  Z = X.T @ Y
  res = np.linalg.inv(K) @ Z
  return res

# Векторы оценок параметров для каждой из 4-х моделей
B_mu = mul_linear_reg_params(X[:, [0]], Y)
B_mu_A = mul_linear_reg_params(X[:, [0, 1]], Y)
B_mu_A_B = mul_linear_reg_params(X[:, [0, 1, 2, 3]], Y)
B_mu_A_B_AB = mul_linear_reg_params(X, Y)

print(f'модель с μ: y = {round(B_mu[0], 2)}')
print(f'модель с μ и αi: y = {round(B_mu_A[0], 2)} + ({round(B_mu_A[1], 2)})*X_A1')
print(f'модель с μ, αi, βj: y = {round(B_mu_A_B[0], 2)} + ({round(B_mu_A_B[1], 2)})*X_A1 + {round(B_mu_A_B[2], 2)}*X_B1 + {round(B_mu_A_B[3], 2)}*X_B2')
print(f'полная модель с μ, αi, βj, γij: y = {round(B_mu_A_B_AB[0], 2)} + {round(B_mu_A_B_AB[1], 2)}*X_A1 + {round(B_mu_A_B_AB[2], 2)}*X_B1 + {round(B_mu_A_B_AB[3], 2)}*X_B2 + ({round(B_mu_A_B_AB[4], 2)})*X_A1_B1 + {round(B_mu_A_B_AB[5], 2)}*X_A1_B2')

модель с μ: y = 1.14
модель с μ и αi: y = 1.13 + (-0.2)*X_A1
модель с μ, αi, βj: y = 1.32 + (-0.07)*X_A1 + 0.93*X_B1 + 1.67*X_B2
полная модель с μ, αi, βj, γij: y = 1.43 + 0.17*X_A1 + 0.75*X_B1 + 1.7*X_B2 + (-0.84)*X_A1_B1 + 1.16*X_A1_B2


In [ ]:
# Найдем суммы квадратов остатков для каждой модели
R_mu = sum([(Y[i] - (B_mu[0]*X[i][0]))**2 for i in range(len(Y))])
R_mu_A = sum([(Y[i] - (B_mu_A[0]*X[i][0] + B_mu_A[1]*X[i][1]))**2 for i in range(len(Y))])
R_mu_A_B = sum([(Y[i] - (B_mu_A_B[0]*X[i][0] + B_mu_A_B[1]*X[i][1] + B_mu_A_B[2]*X[i][2] + B_mu_A_B[3]*X[i][3]))**2 for i in range(len(Y))])
R_mu_A_B_AB = sum([(Y[i] - (B_mu_A_B_AB[0]*X[i][0] + B_mu_A_B_AB[1]*X[i][1] + B_mu_A_B_AB[2]*X[i][2] + B_mu_A_B_AB[3]*X[i][3] + B_mu_A_B_AB[4]*X[i][4] + B_mu_A_B_AB[5]*X[i][5]))**2 for i in range(len(Y))])

# Найдём суммы квадратов для каждого эффекта
SS_A = R_mu - R_mu_A
SS_B = R_mu_A - R_mu_A_B
SS_AB = R_mu_A_B - R_mu_A_B_AB

# Сумма квадратов остатков для полной модели
SS_R = R_mu_A_B_AB

Найдём средние суммы квадратов эффектов и остатков.

In [ ]:
MS_A = SS_A/1 # k-1 степеней свободы, k = 2
MS_B = SS_B/2 # m-1 степеней свободы, m = 3
MS_AB = SS_AB/(1*2) # (k-1)*(m-1) степеней свободы
MS_R = SS_R/(len(Y) - 2*3) # (n - k*m) степеней свободы

Найдём соответствующие статистики Фишера.

In [ ]:
F_A = MS_A/MS_R
F_B = MS_B/MS_R
F_AB = MS_AB/MS_R

print(f'F-статистика, соответствующая эффекту фактора A: {F_A}')
print(f'F-статистика, соответствующая эффекту фактора B: {F_B}')
print(f'F-статистика, соответствующая эффекту взаимодействия факторов A и B: {F_AB}')

F-статистика, соответствующая эффекту фактора A: 0.5943454368086307
F-статистика, соответствующая эффекту фактора B: 11.31028813096684
F-статистика, соответствующая эффекту взаимодействия факторов A и B: 13.003752698870631


$$
\text{Для эффекта фактора A: } α_{набл} = 0,449
$$
$$
\text{Для эффекта фактора B: } α_{набл} = 0,00046
$$
$$
\text{Для эффекта взаимодействия факторов A и B: } α_{набл} = 0,00046
$$

Таким образом, при уровне значимости α = 0.05, эффект фактора A признаётся не значимым, в то время как эффекты фактора B и взаимодействия факторов A и B признаются значимыми.

Проведём анализ значимости попарных различий средних значений отклика для различных уровней фактора B и взаимодействия факторов A и B.

**Метод множественных сравнений Шеффе**

Для проверки гипотезы равенства средних используется статистика:

$$F = \frac{\left( \overline{y}_i - \overline{y}_j \right)^2}{v_1 \, MS_R (1/n_i + 1/n_j)},$$

где:
- $MS_R$ – оценка внутригрупповой (остаточной) дисперсии, полученная в ходе дисперсионного анализа
- $\overline{y}_i$, $\overline{y}_j$ – выборочные средние для групп $i$ и $j$
- $n_i$, $n_j$ – размеры групп $i$ и $j$
- $v_1$ – число степеней свободы для фактора

Если наблюдаемое значение статистики $F_{\text{набл}} \geq F_{\text{кр}}$, то гипотеза о равенстве средних отвергается.

In [ ]:
# Функция для подсчёта среднего группы
def group_mean(group_num, col, Y):
  group_sum = 0
  n = len(col)
  counter = 0
  for i in range(n):
    if col[i] == group_num:
      group_sum += Y[i]
      counter += 1
  return (group_sum/counter, counter)

Для эффекта фактора B:
$$
\text{При } \alpha = 0.05
$$

$$
F_{\text{крит}} = 3{,}4668
$$

In [ ]:
# Проведём сравнение средних для уровней фактора B

# Массив кортежей средних значений для уровней фактора B и размеров групп
B_means_num = [group_mean(i, B, Y) for i in range(1, 4)]

F_B_12 = (B_means_num[0][0] - B_means_num[1][0])**2/(2*MS_R*(1/B_means_num[0][1] + 1/B_means_num[1][1]))
F_B_13 = (B_means_num[0][0] - B_means_num[2][0])**2/(2*MS_R*(1/B_means_num[0][1] + 1/B_means_num[2][1]))
F_B_23 = (B_means_num[1][0] - B_means_num[2][0])**2/(2*MS_R*(1/B_means_num[1][1] + 1/B_means_num[2][1]))

print(f'F-статистика для 1 и 2 групп: {F_B_12}')
print(f'F-статистика для 1 и 3 групп: {F_B_13}')
print(f'F-статистика для 2 и 3 групп: {F_B_23}')

F-статистика для 1 и 2 групп: 0.03818172165096064
F-статистика для 1 и 3 групп: 9.335098181307055
F-статистика для 2 и 3 групп: 6.951879020267155


Таким образом, различия между средними значениями отклика 1-й и 2-й групп фактора B не значимы, среднее значение отклика 3-й группы значимо отличается от средних первых двух групп.

In [ ]:
# Функция для подсчёта среднего комбинации групп двух факторов
def comb_group_mean(group_num_1, group_num_2, col1, col2, Y):
  comb_group_sum = 0
  n = len(Y)
  counter = 0
  for i in range(n):
    if col1[i] == group_num_1 and col2[i] == group_num_2:
      comb_group_sum += Y[i]
      counter += 1
  return (comb_group_sum/counter, counter)

Для эффекта взаимодействия факторов A и B:
$$
\text{При } \alpha = 0.05
$$

$$
F_{\text{крит}} = 3{,}4668
$$

In [ ]:
# Проведём сравнение средних для комбинаций уровней факторов A и B

# Массив кортежей средних значений для комбинаций уровней факторов и их размеров
comb_means_num = [comb_group_mean(i ,j, A, B, Y) for i in range(1, 3) for j in range(1, 4)]

# [(уровень фактора A, уровень фактора B)...] | между элементами comb_means_num и combs установлено взаимооднозначное соответствие
combs = [(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3)]

# Необходимо произвести 15 сравнений. Перебираем все возможные пары комбинаций уровня фактора A и уровня фактора B
for i in range(len(comb_means_num)-1):
  for j in range(i+1, len(comb_means_num)):
    F_AB = (comb_means_num[i][0] - comb_means_num[j][0])**2/(2*MS_R*(1/comb_means_num[i][1] + 1/comb_means_num[j][1]))
    print(f'F-статистика для |{combs[i][0]}_{combs[i][1]}| и |{combs[j][0]}_{combs[j][1]}|: {round(F_AB, 2)} ', '=> различие в средних значимо.' if F_AB > 3.46 else '')

F-статистика для |1_1| и |1_2|: 4.4  => различие в средних значимо.
F-статистика для |1_1| и |1_3|: 5.08  => различие в средних значимо.
F-статистика для |1_1| и |2_1|: 1.11  
F-статистика для |1_1| и |2_2|: 0.94  
F-статистика для |1_1| и |2_3|: 0.38  
F-статистика для |1_2| и |1_3|: 18.67  => различие в средних значимо.
F-статистика для |1_2| и |2_1|: 1.5  
F-статистика для |1_2| и |2_2|: 8.98  => различие в средних значимо.
F-статистика для |1_2| и |2_3|: 7.61  => различие в средних значимо.
F-статистика для |1_3| и |2_1|: 12.73  => различие в средних значимо.
F-статистика для |1_3| и |2_2|: 1.41  
F-статистика для |1_3| и |2_3|: 2.96  
F-статистика для |2_1| и |2_2|: 4.31  => различие в средних значимо.
F-статистика для |2_1| и |2_3|: 3.13  
F-статистика для |2_2| и |2_3|: 0.17  


Анализ различий средних значений отклика для всех возможных комбинаций уровней факторов A и B (взаимодействие A×B) показал, что из 15 возможных пар сравнений:
- 7 пар продемонстрировали статистически значимые различия,
- 8 пар — незначимые различия.

Конкретные пары с выявленными значимыми различиями приведены в выводе выше.

**Вывод**

В ходе данной лабораторной работы, был произведён двухфакторный дисперсионный анализ на основе линейных моделей. Было определено, что эффект фактора A не значим, в то время как эффекты фактора B и взаимодействия факторов A и B значимы.

Для эффекта фактора B и взаимодействия факторов A и B был проведён анализ значимости попарных различий средних значений отклика.

Для эффекта фактора B в результате:
- различия между средними значениями отклика 1-й и 2-й групп не значимы;
- среднее 3-й группы значимо отличается от средних первых двух групп.

Анализ различий средних значений отклика для всех возможных комбинаций уровней факторов A и B (взаимодействие A×B) показал, что из 15 возможных пар сравнений:
- 7 пар продемонстрировали статистически значимые различия;
- 8 пар — незначимые различия.
